# Generated by Django 4.2.7 on 2023-12-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_rename_user_id_order_user_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
