# Generated by Django 4.2.7 on 2023-12-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_product',
        ),
    ]
